# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NO=EE EffectSetting' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NO=EE EffectSetting
pod 'SwiftyJSON'
pod 'Alamofire', '~> 4.5'
pod 'TinyConstraints', :git => 'https://github.com/roberthein/TinyConstraints.git', :branch => 'Release_2.1.2'
pod 'PopupDialog', '0.5.4'
end
